### ISSUE TITLE
Fibank sandbox testing credentials

### ISSUE THREAD

**Issue by big89** [gentor/fibank#1]
Hello, Thanks for the post.

We are integrating fibank sandbox payment gateway in php.
Can you provide sandbox credentials (.pem file and password) for integration testing purpose.

Thanks & Regards,
Logicmaker

**Comment by gentor** [comment]
You can get sandbox credentials only from Fibank, because they are unique for each merchant.
The certificate received from Fibank is in JKS format.
The instructions for converting to .PEM are in the [Readme](https://github.com/gentor/fibank/blob/master/README.md)

**Comment by big89** [comment]
Thanks for your suggestion.
